// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClusterScaleSchedule) DeepCopyInto(out *ClusterScaleSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *ClusterScaleSchedule) DeepCopy() *ClusterScaleSchedule {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleSchedule)
	in.DeepCopyInto(out)
	return out
}
func (in *ClusterScaleSchedule) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ClusterScaleScheduleList) DeepCopyInto(out *ClusterScaleScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ClusterScaleSchedule, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ClusterScaleScheduleList) DeepCopy() *ClusterScaleScheduleList {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleScheduleList)
	in.DeepCopyInto(out)
	return out
}
func (in *ClusterScaleScheduleList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ScaleSchedule) DeepCopyInto(out *ScaleSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *ScaleSchedule) DeepCopy() *ScaleSchedule {
	if in == nil {
		return nil
	}
	out := new(ScaleSchedule)
	in.DeepCopyInto(out)
	return out
}
func (in *ScaleSchedule) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ScaleScheduleList) DeepCopyInto(out *ScaleScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ScaleSchedule, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ScaleScheduleList) DeepCopy() *ScaleScheduleList {
	if in == nil {
		return nil
	}
	out := new(ScaleScheduleList)
	in.DeepCopyInto(out)
	return out
}
func (in *ScaleScheduleList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DeploymentScalePlan) DeepCopyInto(out *DeploymentScalePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *DeploymentScalePlan) DeepCopy() *DeploymentScalePlan {
	if in == nil {
		return nil
	}
	out := new(DeploymentScalePlan)
	in.DeepCopyInto(out)
	return out
}
func (in *DeploymentScalePlan) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DeploymentScalePlanList) DeepCopyInto(out *DeploymentScalePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DeploymentScalePlan, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *DeploymentScalePlanList) DeepCopy() *DeploymentScalePlanList {
	if in == nil {
		return nil
	}
	out := new(DeploymentScalePlanList)
	in.DeepCopyInto(out)
	return out
}
func (in *DeploymentScalePlanList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ScheduleSpec) DeepCopyInto(out *ScheduleSpec) {
	*out = *in
	if in.ValidFrom != nil {
		out.ValidFrom = in.ValidFrom.DeepCopy()
	}
	if in.ValidUntil != nil {
		out.ValidUntil = in.ValidUntil.DeepCopy()
	}
	in.Schedule.DeepCopyInto(&out.Schedule)
}
func (in *ScheduleWindow) DeepCopyInto(out *ScheduleWindow) {
	*out = *in
	if in.Monthly != nil {
		out.Monthly = new(MonthlyWindow)
		*out.Monthly = *in.Monthly
		if in.Monthly.Months != nil {
			out.Monthly.Months = append([]int32(nil), in.Monthly.Months...)
		}
		if in.Monthly.Days != nil {
			out.Monthly.Days = append([]int32(nil), in.Monthly.Days...)
		}
	}
}
func (in *ScheduleStatus) DeepCopyInto(out *ScheduleStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = append([]metav1.Condition(nil), in.Conditions...)
	}
	if in.NextTransitionTime != nil {
		out.NextTransitionTime = in.NextTransitionTime.DeepCopy()
	}
}
func (in *DeploymentScalePlanSpec) DeepCopyInto(out *DeploymentScalePlanSpec) {
	*out = *in
	if in.Rules != nil {
		out.Rules = append([]DeploymentScaleRule(nil), in.Rules...)
	}
	if in.Suspension != nil {
		out.Suspension = new(Suspension)
		*out.Suspension = *in.Suspension
	}
}
func (in *DeploymentScalePlanStatus) DeepCopyInto(out *DeploymentScalePlanStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = append([]metav1.Condition(nil), in.Conditions...)
	}
	if in.DesiredReplicas != nil {
		out.DesiredReplicas = new(int32)
		*out.DesiredReplicas = *in.DesiredReplicas
	}
	if in.CurrentReplicas != nil {
		out.CurrentReplicas = new(int32)
		*out.CurrentReplicas = *in.CurrentReplicas
	}
	if in.LastEvaluationTime != nil {
		out.LastEvaluationTime = in.LastEvaluationTime.DeepCopy()
	}
	if in.NextEvaluationTime != nil {
		out.NextEvaluationTime = in.NextEvaluationTime.DeepCopy()
	}
	if in.LastScaleTime != nil {
		out.LastScaleTime = in.LastScaleTime.DeepCopy()
	}
	if in.LastAppliedReplicas != nil {
		out.LastAppliedReplicas = new(int32)
		*out.LastAppliedReplicas = *in.LastAppliedReplicas
	}
}
